### ISSUE TITLE
update dompdf/dompdf to version 3

### ISSUE THREAD

**Issue by jg-development** [vianetz/pdf-generator#2]
hi,
could you plz update the dompdf/dompdf to version 3?
it has some impacts, caused by requirements.
dompdf/dompdf 3 is using now dompdf/php-font-lib (renamed from phenx/php-font-lib)

**Comment by ma4nn** [comment]
Thanks @jg-development for your suggestions, I have updated the dependencies 👍

**Comment by jg-development** [comment]
Thx, I will Update the lib
